### ISSUE TITLE
Don't version control .ipynb_checkpoints dir

### ISSUE THREAD

**Issue by donoghuc** [donoghuc/data_discussions_r_py#1]
Jupyter will keep a hidden directory .ipynb_checkpoints with a notebook file. Leave this out of the shared repo as it is not necessary and can lead to merge conflicts/unnecessary versioning. 

Proposed action: git rm -r .ipynb_checkpoints in ian_r then possibly add to .gitignore.

**Comment by ianfrantz** [comment]
Resolved.
